"""Physical semantic-v2 snapshot schema and manifest."""

from project_kb.indexing.module_map import SOURCE_ROOT_ORIGIN_VALUES

_SOURCE_ROOT_ORIGIN_CHECK_SQL = ", ".join(f"'{origin}'" for origin in SOURCE_ROOT_ORIGIN_VALUES)

SCHEMA_SQL_V2 = f"""
PRAGMA foreign_keys = ON;
CREATE TABLE snapshot_meta (
    snapshot_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    schema_version INTEGER NOT NULL,
    scanner_version TEXT NOT NULL,
    policy_version TEXT NOT NULL,
    policy_json TEXT NOT NULL,
    extractor_versions_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    repo_root_norm TEXT NOT NULL,
    repository_identity_hash TEXT NOT NULL,
    repository_binding_generation TEXT NOT NULL,
    git_head TEXT,
    git_branch TEXT,
    git_status_fingerprint TEXT NOT NULL,
    repo_state_before_json TEXT NOT NULL,
    repo_state_after_json TEXT NOT NULL,
    build_status TEXT NOT NULL CHECK (build_status IN ('BUILDING', 'SEALED')),
    logical_fingerprint TEXT NOT NULL,
    observation_fingerprint TEXT NOT NULL,
    proof_contract_version TEXT NOT NULL,
    verifier_version TEXT NOT NULL,
    module_map_version TEXT NOT NULL,
    occurrence_contract_version TEXT NOT NULL,
    verification_scope_json TEXT NOT NULL
);
CREATE TABLE files (
    file_id TEXT PRIMARY KEY,
    legacy_file_id TEXT NOT NULL,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    path_key TEXT NOT NULL,
    git_population TEXT NOT NULL,
    file_kind TEXT NOT NULL,
    language TEXT,
    extension TEXT NOT NULL,
    size_bytes INTEGER,
    mtime_ns INTEGER,
    line_count INTEGER,
    encoding TEXT,
    content_hash TEXT,
    analysis_level TEXT NOT NULL,
    classification_reason TEXT NOT NULL,
    parse_status TEXT NOT NULL,
    source_root_id TEXT,
    source_root_path TEXT,
    source_root_origin TEXT CHECK (
        source_root_origin IS NULL
        OR source_root_origin IN ({_SOURCE_ROOT_ORIGIN_CHECK_SQL})
    ),
    module_name TEXT,
    module_resolution_status TEXT NOT NULL,
    module_candidates_json TEXT NOT NULL,
    is_importable INTEGER NOT NULL CHECK (is_importable IN (0, 1)),
    UNIQUE(snapshot_id, path_key),
    UNIQUE(snapshot_id, legacy_file_id)
);
CREATE TABLE pruned_roots (
    pruned_root_id INTEGER PRIMARY KEY,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    category TEXT NOT NULL,
    reason TEXT NOT NULL,
    source_policy TEXT NOT NULL,
    UNIQUE(snapshot_id, relative_path)
);
CREATE TABLE symbols (
    symbol_id TEXT PRIMARY KEY,
    legacy_symbol_id TEXT NOT NULL,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    file_id TEXT NOT NULL REFERENCES files(file_id) ON DELETE CASCADE,
    qualified_name TEXT NOT NULL,
    canonical_qualified_name TEXT,
    logical_key TEXT,
    module_name TEXT,
    short_name TEXT NOT NULL,
    symbol_kind TEXT NOT NULL,
    binding_role TEXT NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    start_column INTEGER NOT NULL,
    end_column INTEGER,
    parent_symbol_id TEXT REFERENCES symbols(symbol_id),
    signature_text TEXT,
    occurrence_ordinal INTEGER NOT NULL,
    occurrence_contract_version TEXT NOT NULL,
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    UNIQUE(snapshot_id, legacy_symbol_id)
);
CREATE TABLE imports (
    import_id TEXT PRIMARY KEY,
    legacy_import_id TEXT NOT NULL,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    file_id TEXT NOT NULL REFERENCES files(file_id) ON DELETE CASCADE,
    import_kind TEXT NOT NULL,
    module_text TEXT NOT NULL,
    imported_name TEXT,
    alias TEXT,
    relative_level INTEGER NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    resolution_status TEXT NOT NULL,
    resolved_file_id TEXT REFERENCES files(file_id),
    normalized_module_name TEXT,
    v2_resolution_status TEXT NOT NULL,
    v2_resolved_file_id TEXT REFERENCES files(file_id),
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    UNIQUE(snapshot_id, legacy_import_id)
);
CREATE TABLE relations (
    relation_id TEXT PRIMARY KEY,
    legacy_relation_id TEXT NOT NULL,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    relation_kind TEXT NOT NULL,
    source_file_id TEXT REFERENCES files(file_id),
    source_symbol_id TEXT REFERENCES symbols(symbol_id),
    target_file_id TEXT REFERENCES files(file_id),
    target_symbol_id TEXT REFERENCES symbols(symbol_id),
    target_text TEXT,
    start_line INTEGER,
    end_line INTEGER,
    start_column INTEGER,
    end_column INTEGER,
    resolution_status TEXT NOT NULL,
    evidence_kind TEXT NOT NULL,
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    UNIQUE(snapshot_id, legacy_relation_id)
);
CREATE TABLE parse_diagnostics (
    diagnostic_id INTEGER PRIMARY KEY,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    file_id TEXT NOT NULL REFERENCES files(file_id) ON DELETE CASCADE,
    diagnostic_kind TEXT NOT NULL,
    message TEXT NOT NULL,
    line INTEGER,
    column INTEGER,
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL
);
CREATE TABLE proof_manifest (
    proof_id TEXT PRIMARY KEY,
    snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id) ON DELETE CASCADE,
    file_id TEXT REFERENCES files(file_id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    path_key TEXT NOT NULL,
    git_population TEXT NOT NULL,
    proof_class TEXT NOT NULL CHECK (
        proof_class IN (
            'CONTENT_HASH', 'BOUNDED_METADATA',
            'EXCLUDED_HARD_SECRET', 'EXCLUDED_PRUNED'
        )
    ),
    evidence_kind TEXT NOT NULL,
    stat_signature_json TEXT,
    content_hash TEXT,
    verification_scope TEXT NOT NULL CHECK (
        verification_scope IN ('STRUCTURAL_CONTENT', 'METADATA_ONLY', 'EXCLUDED')
    ),
    exclusion_reason TEXT,
    UNIQUE(snapshot_id, path_key)
);
CREATE TABLE index_runs (
    run_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT NOT NULL,
    status TEXT NOT NULL,
    failure_code TEXT,
    candidate_count INTEGER NOT NULL,
    candidate_bytes INTEGER NOT NULL,
    metadata_only_count INTEGER NOT NULL,
    pruned_root_count INTEGER NOT NULL,
    text_file_count INTEGER NOT NULL,
    parsed_file_count INTEGER NOT NULL,
    parse_failure_count INTEGER NOT NULL,
    symbol_count INTEGER NOT NULL,
    import_count INTEGER NOT NULL,
    relation_count INTEGER NOT NULL,
    enumeration_ms INTEGER NOT NULL,
    classification_ms INTEGER NOT NULL,
    read_hash_ms INTEGER NOT NULL,
    parse_ms INTEGER NOT NULL,
    relations_ms INTEGER NOT NULL,
    database_write_ms INTEGER NOT NULL,
    total_ms INTEGER NOT NULL,
    snapshot_size_bytes INTEGER NOT NULL,
    published_snapshot_id TEXT NOT NULL REFERENCES snapshot_meta(snapshot_id),
    warnings_json TEXT NOT NULL
);
CREATE INDEX files_relative_path_idx ON files(relative_path);
CREATE INDEX files_module_name_idx ON files(module_name, path_key);
CREATE INDEX symbols_short_name_idx ON symbols(short_name, qualified_name);
CREATE INDEX symbols_file_idx ON symbols(file_id, start_line);
CREATE INDEX symbols_logical_key_idx ON symbols(logical_key, symbol_id);
CREATE INDEX imports_file_idx ON imports(file_id, start_line);
CREATE INDEX relations_kind_idx ON relations(relation_kind);
CREATE INDEX diagnostics_file_idx ON parse_diagnostics(file_id, line);
CREATE INDEX proof_manifest_path_idx ON proof_manifest(path_key);
"""

REQUIRED_TABLE_COLUMNS_V2 = {
    "snapshot_meta": {
        "snapshot_id",
        "project_id",
        "run_id",
        "schema_version",
        "scanner_version",
        "policy_version",
        "policy_json",
        "extractor_versions_json",
        "created_at",
        "repo_root_norm",
        "repository_identity_hash",
        "repository_binding_generation",
        "git_head",
        "git_branch",
        "git_status_fingerprint",
        "repo_state_before_json",
        "repo_state_after_json",
        "build_status",
        "logical_fingerprint",
        "observation_fingerprint",
        "proof_contract_version",
        "verifier_version",
        "module_map_version",
        "occurrence_contract_version",
        "verification_scope_json",
    },
    "files": {
        "file_id",
        "legacy_file_id",
        "snapshot_id",
        "relative_path",
        "path_key",
        "git_population",
        "file_kind",
        "language",
        "extension",
        "size_bytes",
        "mtime_ns",
        "line_count",
        "encoding",
        "content_hash",
        "analysis_level",
        "classification_reason",
        "parse_status",
        "source_root_id",
        "source_root_path",
        "source_root_origin",
        "module_name",
        "module_resolution_status",
        "module_candidates_json",
        "is_importable",
    },
    "pruned_roots": {
        "pruned_root_id",
        "snapshot_id",
        "relative_path",
        "category",
        "reason",
        "source_policy",
    },
    "symbols": {
        "symbol_id",
        "legacy_symbol_id",
        "snapshot_id",
        "file_id",
        "qualified_name",
        "canonical_qualified_name",
        "logical_key",
        "module_name",
        "short_name",
        "symbol_kind",
        "binding_role",
        "start_line",
        "end_line",
        "start_column",
        "end_column",
        "parent_symbol_id",
        "signature_text",
        "occurrence_ordinal",
        "occurrence_contract_version",
        "extractor_name",
        "extractor_version",
    },
    "imports": {
        "import_id",
        "legacy_import_id",
        "snapshot_id",
        "file_id",
        "import_kind",
        "module_text",
        "imported_name",
        "alias",
        "relative_level",
        "start_line",
        "end_line",
        "resolution_status",
        "resolved_file_id",
        "normalized_module_name",
        "v2_resolution_status",
        "v2_resolved_file_id",
        "extractor_name",
        "extractor_version",
    },
    "relations": {
        "relation_id",
        "legacy_relation_id",
        "snapshot_id",
        "relation_kind",
        "source_file_id",
        "source_symbol_id",
        "target_file_id",
        "target_symbol_id",
        "target_text",
        "start_line",
        "end_line",
        "start_column",
        "end_column",
        "resolution_status",
        "evidence_kind",
        "extractor_name",
        "extractor_version",
    },
    "parse_diagnostics": {
        "diagnostic_id",
        "snapshot_id",
        "file_id",
        "diagnostic_kind",
        "message",
        "line",
        "column",
        "extractor_name",
        "extractor_version",
    },
    "proof_manifest": {
        "proof_id",
        "snapshot_id",
        "file_id",
        "relative_path",
        "path_key",
        "git_population",
        "proof_class",
        "evidence_kind",
        "stat_signature_json",
        "content_hash",
        "verification_scope",
        "exclusion_reason",
    },
    "index_runs": {
        "run_id",
        "project_id",
        "started_at",
        "finished_at",
        "status",
        "failure_code",
        "candidate_count",
        "candidate_bytes",
        "metadata_only_count",
        "pruned_root_count",
        "text_file_count",
        "parsed_file_count",
        "parse_failure_count",
        "symbol_count",
        "import_count",
        "relation_count",
        "enumeration_ms",
        "classification_ms",
        "read_hash_ms",
        "parse_ms",
        "relations_ms",
        "database_write_ms",
        "total_ms",
        "snapshot_size_bytes",
        "published_snapshot_id",
        "warnings_json",
    },
}

REQUIRED_INDEXES_V2 = {
    "files_relative_path_idx",
    "files_module_name_idx",
    "symbols_short_name_idx",
    "symbols_file_idx",
    "symbols_logical_key_idx",
    "imports_file_idx",
    "relations_kind_idx",
    "diagnostics_file_idx",
    "proof_manifest_path_idx",
}
