[project]
name = "project-kb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vlad", email = "cuvka000@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
project-kb = "project_kb:main"

[build-system]
requires = ["uv_build>=0.11.9,<0.12.0"]
build-backend = "uv_build"
