"""Process exit code constants for the Project KB CLI."""

OK = 0
INTERNAL_ERROR = 1
USAGE_ERROR = 2
NOT_IMPLEMENTED = 3
PROJECT_NOT_REGISTERED = 10
REGISTRY_ERROR = 15
REPO_PATH_ERROR = 16
GIT_REPO_ERROR = 17
DESTRUCTIVE_CONFIRMATION_REQUIRED = 18
